// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0--rc2
// source: spaces_special_chars.proto

package simple

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 测试值中包含空格与特殊字符，逗号左右可有空格
type SpacesAroundSpecials struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             int32                  `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty" k1:"v1" k2:"v2 , v22 , v222"`     // tags: `k1:" v1 " k2:" v2 , v22 , v222 "`
	B             string                 `protobuf:"bytes,2,opt,name=b,proto3" json:"b,omitempty" k3:"v3 , v33 , v333"`              // tags: `json:"b,omitempty" k3:" v3 , v33 , v333 "`
	C             string                 `protobuf:"bytes,3,opt,name=c,proto3" json:"c,omitempty" k5:"a,b , c , d" k4:"(x) {y} [z]"` // tags: `k4:"(x) {y} [z]" k5:"a,b , c , d"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpacesAroundSpecials) Reset() {
	*x = SpacesAroundSpecials{}
	mi := &file_spaces_special_chars_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpacesAroundSpecials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpacesAroundSpecials) ProtoMessage() {}

func (x *SpacesAroundSpecials) ProtoReflect() protoreflect.Message {
	mi := &file_spaces_special_chars_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpacesAroundSpecials.ProtoReflect.Descriptor instead.
func (*SpacesAroundSpecials) Descriptor() ([]byte, []int) {
	return file_spaces_special_chars_proto_rawDescGZIP(), []int{0}
}

func (x *SpacesAroundSpecials) GetA() int32 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *SpacesAroundSpecials) GetB() string {
	if x != nil {
		return x.B
	}
	return ""
}

func (x *SpacesAroundSpecials) GetC() string {
	if x != nil {
		return x.C
	}
	return ""
}

var File_spaces_special_chars_proto protoreflect.FileDescriptor

const file_spaces_special_chars_proto_rawDesc = "" +
	"\n" +
	"\x1aspaces_special_chars.proto\x12\x1agoproto.protoc.custom_tags\"@\n" +
	"\x14SpacesAroundSpecials\x12\f\n" +
	"\x01a\x18\x01 \x01(\x05R\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\tR\x01b\x12\f\n" +
	"\x01c\x18\x03 \x01(\tR\x01cBAZ?github.com/example/protobuf-example/testdata/custom_tags;simpleb\x06proto3"

var (
	file_spaces_special_chars_proto_rawDescOnce sync.Once
	file_spaces_special_chars_proto_rawDescData []byte
)

func file_spaces_special_chars_proto_rawDescGZIP() []byte {
	file_spaces_special_chars_proto_rawDescOnce.Do(func() {
		file_spaces_special_chars_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spaces_special_chars_proto_rawDesc), len(file_spaces_special_chars_proto_rawDesc)))
	})
	return file_spaces_special_chars_proto_rawDescData
}

var file_spaces_special_chars_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_spaces_special_chars_proto_goTypes = []any{
	(*SpacesAroundSpecials)(nil), // 0: goproto.protoc.custom_tags.SpacesAroundSpecials
}
var file_spaces_special_chars_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_spaces_special_chars_proto_init() }
func file_spaces_special_chars_proto_init() {
	if File_spaces_special_chars_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spaces_special_chars_proto_rawDesc), len(file_spaces_special_chars_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spaces_special_chars_proto_goTypes,
		DependencyIndexes: file_spaces_special_chars_proto_depIdxs,
		MessageInfos:      file_spaces_special_chars_proto_msgTypes,
	}.Build()
	File_spaces_special_chars_proto = out.File
	file_spaces_special_chars_proto_goTypes = nil
	file_spaces_special_chars_proto_depIdxs = nil
}
