// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0--rc2
// source: tags_with_extra_comments.proto

package simple

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 尾注释中 tags: `...` 前后均可有说明文字
type TagsWithExtraComments struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" k1:"v1" k2:"v2"`        // 说明: 此字段测试 tags: `k1:"v1" k2:"v2"` 附注
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" k1:"v1"`             // 有前后文字 tags: `json:"name,omitempty" k1:"v1"` 更多文本
	Note          string                 `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty" k1:"v 1" k2:"v-2_2"` // 末尾说明 tags: `k1:"v 1" k2:"v-2_2"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagsWithExtraComments) Reset() {
	*x = TagsWithExtraComments{}
	mi := &file_tags_with_extra_comments_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagsWithExtraComments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagsWithExtraComments) ProtoMessage() {}

func (x *TagsWithExtraComments) ProtoReflect() protoreflect.Message {
	mi := &file_tags_with_extra_comments_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagsWithExtraComments.ProtoReflect.Descriptor instead.
func (*TagsWithExtraComments) Descriptor() ([]byte, []int) {
	return file_tags_with_extra_comments_proto_rawDescGZIP(), []int{0}
}

func (x *TagsWithExtraComments) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TagsWithExtraComments) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TagsWithExtraComments) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

var File_tags_with_extra_comments_proto protoreflect.FileDescriptor

const file_tags_with_extra_comments_proto_rawDesc = "" +
	"\n" +
	"\x1etags_with_extra_comments.proto\x12\x1agoproto.protoc.custom_tags\"O\n" +
	"\x15TagsWithExtraComments\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04note\x18\x03 \x01(\tR\x04noteBAZ?github.com/example/protobuf-example/testdata/custom_tags;simpleb\x06proto3"

var (
	file_tags_with_extra_comments_proto_rawDescOnce sync.Once
	file_tags_with_extra_comments_proto_rawDescData []byte
)

func file_tags_with_extra_comments_proto_rawDescGZIP() []byte {
	file_tags_with_extra_comments_proto_rawDescOnce.Do(func() {
		file_tags_with_extra_comments_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tags_with_extra_comments_proto_rawDesc), len(file_tags_with_extra_comments_proto_rawDesc)))
	})
	return file_tags_with_extra_comments_proto_rawDescData
}

var file_tags_with_extra_comments_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tags_with_extra_comments_proto_goTypes = []any{
	(*TagsWithExtraComments)(nil), // 0: goproto.protoc.custom_tags.TagsWithExtraComments
}
var file_tags_with_extra_comments_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tags_with_extra_comments_proto_init() }
func file_tags_with_extra_comments_proto_init() {
	if File_tags_with_extra_comments_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tags_with_extra_comments_proto_rawDesc), len(file_tags_with_extra_comments_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tags_with_extra_comments_proto_goTypes,
		DependencyIndexes: file_tags_with_extra_comments_proto_depIdxs,
		MessageInfos:      file_tags_with_extra_comments_proto_msgTypes,
	}.Build()
	File_tags_with_extra_comments_proto = out.File
	file_tags_with_extra_comments_proto_goTypes = nil
	file_tags_with_extra_comments_proto_depIdxs = nil
}
