// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0--rc2
// source: trailing_comments.proto

package simple

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrailingCommentsTags struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" k1:"v1" k2:"v2" k3:"v3,v33,v333"` // tags: `k1:"v1" k2:"v2" k3:"v3,v33,v333"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" k1:"v1" k2:"v2"`               // tags: `k1:"v1" k2:"v2"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty" k1:"v1"`                     // tags: `k1:"v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrailingCommentsTags) Reset() {
	*x = TrailingCommentsTags{}
	mi := &file_trailing_comments_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrailingCommentsTags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrailingCommentsTags) ProtoMessage() {}

func (x *TrailingCommentsTags) ProtoReflect() protoreflect.Message {
	mi := &file_trailing_comments_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrailingCommentsTags.ProtoReflect.Descriptor instead.
func (*TrailingCommentsTags) Descriptor() ([]byte, []int) {
	return file_trailing_comments_proto_rawDescGZIP(), []int{0}
}

func (x *TrailingCommentsTags) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TrailingCommentsTags) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TrailingCommentsTags) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

var File_trailing_comments_proto protoreflect.FileDescriptor

const file_trailing_comments_proto_rawDesc = "" +
	"\n" +
	"\x17trailing_comments.proto\x12\x1agoproto.protoc.custom_tags\"P\n" +
	"\x14TrailingCommentsTags\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phoneBAZ?github.com/example/protobuf-example/testdata/custom_tags;simpleb\x06proto3"

var (
	file_trailing_comments_proto_rawDescOnce sync.Once
	file_trailing_comments_proto_rawDescData []byte
)

func file_trailing_comments_proto_rawDescGZIP() []byte {
	file_trailing_comments_proto_rawDescOnce.Do(func() {
		file_trailing_comments_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trailing_comments_proto_rawDesc), len(file_trailing_comments_proto_rawDesc)))
	})
	return file_trailing_comments_proto_rawDescData
}

var file_trailing_comments_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_trailing_comments_proto_goTypes = []any{
	(*TrailingCommentsTags)(nil), // 0: goproto.protoc.custom_tags.TrailingCommentsTags
}
var file_trailing_comments_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_trailing_comments_proto_init() }
func file_trailing_comments_proto_init() {
	if File_trailing_comments_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trailing_comments_proto_rawDesc), len(file_trailing_comments_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_trailing_comments_proto_goTypes,
		DependencyIndexes: file_trailing_comments_proto_depIdxs,
		MessageInfos:      file_trailing_comments_proto_msgTypes,
	}.Build()
	File_trailing_comments_proto = out.File
	file_trailing_comments_proto_goTypes = nil
	file_trailing_comments_proto_depIdxs = nil
}
